name: flows
description: Provides a new scope for streams, handling special cases such as infinite streams.
version: 0.1.0
repository: https://github.com/beet-software/dart-flows

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  path: ^1.8.1
  test: ^1.16.0
  lints: ^1.0.0
